### ISSUE TITLE
issue in reading .woff/.ttf/.woff2 (font extension) files

### ISSUE THREAD

**Issue by arvindjangra1996** [jordaneremieff/mangum#160] opened 2021-02-08 07:14 UTC
Hi. There is an issue in reading font files from the AWS API gateway proxied to AWS Lambda.
It is reading it as a text file.

in protocols/http.py 
body is not encoded in base64 `body = base64.b64encode(body)`
and giving error in `self.response["body"] = body.decode()`

It should return header with content-type as font/*

**Comment by 0x2b3bfa0** [comment] 2021-02-13 22:37
I don't have time to devise a better way for guessing the right mime types, but managed to fix it with [a quick hack](https://github.com/0x2b3bfa0/mangum/compare/main...0x2b3bfa0:base64?expand=1) for a last-minute deployment.

```python
Traceback (most recent call last):
File "/var/lang/lib/python3.8/site-packages/mangum/protocols/http.py", line 79, in run
await app(self.scope, self.receive, self.send)
File "/var/lang/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
await super().__call__(scope, receive, send)
File "/var/lang/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
await self.middleware_stack(scope, receive, send)
File "/var/lang/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
raise exc from None
File "/var/lang/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
await self.app(scope, receive, _send)
File "/var/lang/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
raise exc from None
File "/var/lang/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
await self.app(scope, receive, sender)
File "/var/lang/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
await route.handle(scope, receive, send)
File "/var/lang/lib/python3.8/site-packages/starlette/routing.py", line 376, in handle
await self.app(scope, receive, send)
File "/var/lang/lib/python3.8/site-packages/starlette/staticfiles.py", line 94, in __call__
await response(scope, receive, send)
File "/var/lang/lib/python3.8/site-packages/starlette/responses.py", line 310, in __call__
await send(
File "/var/lang/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
await send(message)
File "/var/lang/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in _send
await send(message)
File "/var/lang/lib/python3.8/site-packages/mangum/protocols/http.py", line 162, in send
self.response["body"] = body.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 10: invalid start byte
```

I guess that, at least for this specific edge case, it would be possibe to try decoding the body to a `str` first, and, in case it raises `UnicodeDecodeError`, fallback to Base64 encoding. Dealing with MIME types for determining the "binaryness" of the content doesn't seem like the best idea in the world.

**Comment by 0x2b3bfa0** [comment] 2021-02-13 23:46
I've fixed it with a quick hack, setting all the media types as binary on `serverless.yml` and [bypassing the affected logic](https://github.com/0x2b3bfa0/mangum/compare/main...0x2b3bfa0:base64?expand=1), but there must be an elegant solution.

```yaml
service: ${env:NAME}

provider:
  name: aws
  region: ${env:AWS_REGION}
  stage: ${env:STAGE}
  logs:
    httpApi: true
  apiGateway:
    binaryMediaTypes:
      - '*/*'
      
functions:
  main:
    events:
      - httpApi:
          path: '*'
    image: ${env:IMAGE}
    memorySize: 128
```

_Since https://github.com/serverless/serverless/pull/6063 it's possible to enforce bynary media types with a custom `binaryMediaTypes` field._

**Comment by koxudaxi** [comment] 2021-02-14 14:07
Thank you for creating this issue.

Interesting.
I found the  related code
https://github.com/jordaneremieff/mangum/blob/ded6a55a3ca65c26bf9228ed8d78c2a72bb9c82b/mangum/protocols/http.py#L200-L207

We can't add all target extension in the condition.
I will think of the solution. 
Also, we welcome suggestions and ideas.

**Comment by 0x2b3bfa0** [comment] 2021-02-14 14:36
I'm not an expert on API Gateway, but it looks like this has something to do with the contrived rules documented here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-workflow.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html
As a curiosity, serving a [`site.webmanifest`] file with [FastAPI Static Files](https://fastapi.tiangolo.com/tutorial/static-files/) returns raw Base64 data instead of the file contents.

**Comment by koxudaxi** [comment] 2021-02-14 14:42
Thank you for posting the links.
I will check it :)
Also, we need to discuss behavior when `mangum` can't detect the type.

**Comment by daviwesley** [comment] 2021-02-23 21:11
> I've fixed it with a quick hack, setting all the media types as binary on `serverless.yml` and [bypassing the affected logic](https://github.com/0x2b3bfa0/mangum/compare/main...0x2b3bfa0:base64?expand=1), but there must be an elegant solution.
> 
> ```yaml
> service: ${env:NAME}
> 
> provider:
>   name: aws
>   region: ${env:AWS_REGION}
>   stage: ${env:STAGE}
>   logs:
>     httpApi: true
>   apiGateway:
>     binaryMediaTypes:
>       - '*/*'
>       
> functions:
>   main:
>     events:
>       - httpApi: '*'
>     image: ${env:IMAGE}
>     memorySize: 128
> ```
> 
> _Since [serverless/serverless#6063](https://github.com/serverless/serverless/pull/6063) it's possible to enforce binary media types with a custom `binaryMediaTypes` field._

@0x2b3bfa0 
what boilerplate/tools did you use to integrate mangum and serverless framework?

**Comment by 0x2b3bfa0** [comment] 2021-02-23 23:32
@daviwesley, I wrote the boilerplate myself for an internal application; please take a look here for a bare bones example: https://github.com/0x2b3bfa0/python-xi

I don't have time to document and maintain it decently, but would be glad to merge a few solid pull requests. 😄

**Comment by bohana** [comment] 2021-03-19 11:15
Possibly related (if you use SAM to deploy AWS API Gateway):
https://github.com/aws/serverless-application-model/issues/566

I got the binary media types defined at the gateway but still could not get the API to convert base64 -> binary on delivery...

**Comment by four43** [comment] 2021-03-20 14:07
Without a suuuuuuper concrete answer to work off of, #170 should fix this too. We're handling juggling of text and binary data better.

**Comment by jordaneremieff** [comment] 2021-03-22 15:10
Is anyone able to confirm if the change from @four43 (mentioned above) resolved this? I'll close this for now, but if the issue persists with the main branch changes then please comment.

**Closed by jordaneremieff** 2021-03-22 15:10 UTC

**Comment by brolewis** [comment] 2021-04-21 16:04
> Is anyone able to confirm if the change from @four43 (mentioned above) resolved this? I'll close this for now, but if the issue persists with the main branch changes then please comment.

@jordaneremieff As some that was having problem with fonts on `0.11.0`, I can confirm that @four43's fix does indeed fix the error. In that vein, if a new release could be cut as well, I would be grateful.

**Comment by jordaneremieff** [comment] 2021-05-08 04:58
@brolewis thank you for confirming. I wanted to go through all the new ALB behavior that was merged in a few weeks ago before the next release. - I'll try to do one soon.
