### ISSUE TITLE
How can I log the response?

### ISSUE THREAD

**Issue by burritoIand** [jordaneremieff/mangum#159] opened 2021-02-07 02:14 UTC
I'd like to log both the full request and full response.

Currently I am logging the full request by using a custom middleware as below:
```
class AWSLoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        logger.info(f'{request.scope.get("aws.event")}')

        response = await call_next(request)

        return response
```
How could I also log the full response back to aws?

**Comment by tuukkamustonen** [comment] 2021-02-11 15:52
Can't you just `log.info()` whatever you need after the `response = await call_next(request)` line?

**Comment by koxudaxi** [comment] 2021-02-14 14:13
@burritoIand 
Did you have any updates? 
I support the answer of @tuukkamustonen

**Comment by jordaneremieff** [comment] 2021-02-24 09:33
Closing this for now based on the previous comments  - can reopen if the issue is deeper.

**Closed by jordaneremieff** 2021-02-24 09:33 UTC

**Comment by erichonkanen** [comment] 2021-11-09 01:43
hey @tuukkamustonen @koxudaxi @jordaneremieff I just got back to this and the problem is that unlike the request, the response does not have a `scope` or any other information other than the status code.
```
dir(response)

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'background', 'body_iterator', 'charset', 'delete_cookie', 'headers', 'init_headers', 'listen_for_disconnect', 'media_type', 'raw_headers', 'render', 'set_cookie', 'status_code', 'stream_response']
```
